# Generated by Django 5.2.10 on 2026-01-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kutubxonachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('ish_vaqti', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kutubxonachi',
                'verbose_name_plural': 'Kutubxonachilar',
            },
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('jins', models.CharField(choices=[('Erkak,', 'Erkak'), ('Ayol', 'Ayol')], max_length=20)),
                ('t_sana', models.DateField(blank=True, null=True)),
                ('kitob_soni', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tirik', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('guruh', models.CharField(blank=True, max_length=255, null=True)),
                ('kurs', models.PositiveIntegerField(default=1)),
                ('kitob_soni', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabas',
            },
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('janr', models.CharField(max_length=50)),
                ('sahifa', models.PositiveSmallIntegerField()),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.muallif')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_sana', models.DateTimeField(auto_now_add=True)),
                ('qaytargan_sana', models.DateField(blank=True, null=True)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kitob')),
                ('kutubxonachi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kutubxonachi')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.talaba')),
            ],
            options={
                'verbose_name': 'Record Talaba',
                'verbose_name_plural': 'Record Talabalar',
            },
        ),
    ]
